create table if not exists public.cp_contacts (
  id bigint generated by default as identity primary key,
  organization text not null,
  cp_name text,
  status text,
  joined_date text,
  agreement_end_date text,
  contact_emails text,
  email_domain text,
  note text,
  row_data jsonb not null default '{}'::jsonb,
  source text not null default 'apps_script',
  synced_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.cp_contacts add column if not exists source text not null default 'apps_script';
alter table public.cp_contacts add column if not exists updated_at timestamptz not null default now();

create index if not exists cp_contacts_organization_idx
  on public.cp_contacts (organization);

create index if not exists cp_contacts_synced_at_idx
  on public.cp_contacts (synced_at desc);

alter table public.cp_contacts enable row level security;

drop policy if exists "Users can read cp contacts" on public.cp_contacts;
drop policy if exists "Users can insert cp contacts" on public.cp_contacts;
drop policy if exists "Users can update cp contacts" on public.cp_contacts;
drop policy if exists "Users can delete cp contacts" on public.cp_contacts;

create policy "Users can read cp contacts"
  on public.cp_contacts
  for select
  to authenticated
  using (true);

create policy "Users can insert cp contacts"
  on public.cp_contacts
  for insert
  to authenticated
  with check (true);

create policy "Users can update cp contacts"
  on public.cp_contacts
  for update
  to authenticated
  using (true);

create policy "Users can delete cp contacts"
  on public.cp_contacts
  for delete
  to authenticated
  using (true);
