create table if not exists public.credit_report_rows (
  id bigint generated by default as identity primary key,
  upload_id uuid not null references public.credit_report_uploads(id) on delete cascade,
  cp text not null,
  report_type text not null check (report_type in ('project', 'admin_logs')),
  sheet_name text not null,
  row_index integer not null,
  row_data jsonb not null,
  uploaded_at timestamptz not null default now()
);

create index if not exists credit_report_rows_upload_id_idx
  on public.credit_report_rows (upload_id);

create index if not exists credit_report_rows_cp_report_type_idx
  on public.credit_report_rows (cp, report_type);

alter table public.credit_report_rows enable row level security;

drop policy if exists "Users can read credit report rows" on public.credit_report_rows;
drop policy if exists "Users can insert credit report rows" on public.credit_report_rows;
drop policy if exists "Users can delete credit report rows" on public.credit_report_rows;

create policy "Users can read credit report rows"
  on public.credit_report_rows
  for select
  to authenticated
  using (true);

create policy "Users can insert credit report rows"
  on public.credit_report_rows
  for insert
  to authenticated
  with check (true);

create policy "Users can delete credit report rows"
  on public.credit_report_rows
  for delete
  to authenticated
  using (true);
