create table if not exists public.credit_usage_logs (
  id bigint generated by default as identity primary key,
  cp_partner text not null,
  transaction_date date not null,
  description text not null,
  amount numeric not null,
  actions text
);

create index if not exists credit_usage_logs_cp_partner_idx
  on public.credit_usage_logs (cp_partner);

create index if not exists credit_usage_logs_transaction_date_idx
  on public.credit_usage_logs (transaction_date desc);

alter table public.credit_usage_logs enable row level security;

drop policy if exists "Users can read credit usage logs" on public.credit_usage_logs;

create policy "Users can read credit usage logs"
  on public.credit_usage_logs
  for select
  to authenticated
  using (true);

drop policy if exists "Users can insert credit usage logs" on public.credit_usage_logs;
drop policy if exists "Users can delete credit usage logs" on public.credit_usage_logs;

create policy "Users can insert credit usage logs"
  on public.credit_usage_logs
  for insert
  to authenticated
  with check (true);

create policy "Users can delete credit usage logs"
  on public.credit_usage_logs
  for delete
  to authenticated
  using (true);

create table if not exists public.partner_credit_balances (
  id bigint generated by default as identity primary key,
  partner text not null unique,
  credits_allocated numeric not null default 0,
  credits_remaining numeric not null default 0,
  updated_at timestamptz not null default now()
);

alter table public.partner_credit_balances enable row level security;

drop policy if exists "Users can read partner credit balances" on public.partner_credit_balances;

create policy "Users can read partner credit balances"
  on public.partner_credit_balances
  for select
  to authenticated
  using (true);
