-- CP Revenue Dashboard — run once in Supabase SQL Editor
-- Project: https://supabase.com/dashboard/project/xfxkljltzyqvgbombtqy/sql/new

-- ========== enforce_gametize_email_domain.sql ==========
-- Restrict Supabase Auth to @gametize.com emails (sign-up and email changes).
-- OAuth first-time sign-in also creates an auth.users row, so INSERT is covered.

create or replace function public.enforce_gametize_email_domain()
returns trigger
language plpgsql
security definer
set search_path = auth, public
as $$
begin
  if new.email is null or lower(trim(new.email)) not like '%@gametize.com' then
    raise exception 'Only @gametize.com email addresses are allowed to sign up or sign in'
      using errcode = 'P0001';
  end if;

  return new;
end;
$$;

drop trigger if exists enforce_gametize_email_domain_insert on auth.users;

create trigger enforce_gametize_email_domain_insert
  before insert on auth.users
  for each row
  execute function public.enforce_gametize_email_domain();

drop trigger if exists enforce_gametize_email_domain_update on auth.users;

create trigger enforce_gametize_email_domain_update
  before update of email on auth.users
  for each row
  when (new.email is distinct from old.email)
  execute function public.enforce_gametize_email_domain();

-- ========== stripe_invoices_table.sql ==========
create table if not exists public.stripe_invoices (
  id bigint generated by default as identity primary key,
  upload_id uuid not null,
  source_file text not null,
  row_index integer not null,
  uploaded_by uuid references auth.users(id),
  uploaded_at timestamptz not null default now(),
  stripe_invoice_id text,
  organization text,
  customer_email text,
  date_utc text,
  subtotal text,
  tax_amount text,
  total_amount text,
  total_before_gst text,
  total_discount_amount text,
  credits_usage text,
  raw_data jsonb not null
);

create index if not exists stripe_invoices_upload_id_idx
  on public.stripe_invoices (upload_id);

create index if not exists stripe_invoices_uploaded_at_idx
  on public.stripe_invoices (uploaded_at desc);

create index if not exists stripe_invoices_customer_email_idx
  on public.stripe_invoices (customer_email);

create index if not exists stripe_invoices_organization_idx
  on public.stripe_invoices (organization);

alter table public.stripe_invoices enable row level security;

drop policy if exists "Users can read uploaded Stripe invoices" on public.stripe_invoices;

create policy "Users can read uploaded Stripe invoices"
  on public.stripe_invoices
  for select
  to authenticated
  using (true);

-- ========== credit_usage_logs_table.sql ==========
create table if not exists public.credit_usage_logs (
  id bigint generated by default as identity primary key,
  cp_partner text not null,
  transaction_date date not null,
  description text not null,
  amount numeric not null,
  actions text
);

create index if not exists credit_usage_logs_cp_partner_idx
  on public.credit_usage_logs (cp_partner);

create index if not exists credit_usage_logs_transaction_date_idx
  on public.credit_usage_logs (transaction_date desc);

alter table public.credit_usage_logs enable row level security;

drop policy if exists "Users can read credit usage logs" on public.credit_usage_logs;

create policy "Users can read credit usage logs"
  on public.credit_usage_logs
  for select
  to authenticated
  using (true);

drop policy if exists "Users can insert credit usage logs" on public.credit_usage_logs;
drop policy if exists "Users can delete credit usage logs" on public.credit_usage_logs;

create policy "Users can insert credit usage logs"
  on public.credit_usage_logs
  for insert
  to authenticated
  with check (true);

create policy "Users can delete credit usage logs"
  on public.credit_usage_logs
  for delete
  to authenticated
  using (true);

create table if not exists public.partner_credit_balances (
  id bigint generated by default as identity primary key,
  partner text not null unique,
  credits_allocated numeric not null default 0,
  credits_remaining numeric not null default 0,
  updated_at timestamptz not null default now()
);

alter table public.partner_credit_balances enable row level security;

drop policy if exists "Users can read partner credit balances" on public.partner_credit_balances;

create policy "Users can read partner credit balances"
  on public.partner_credit_balances
  for select
  to authenticated
  using (true);

-- ========== credit_report_uploads.sql ==========
insert into storage.buckets (id, name, public, file_size_limit)
values ('credit-reports', 'credit-reports', false, 52428800)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit;

drop policy if exists "Authenticated users can upload credit reports" on storage.objects;
drop policy if exists "Authenticated users can read credit reports" on storage.objects;

create policy "Authenticated users can upload credit reports"
  on storage.objects
  for insert
  to authenticated
  with check (bucket_id = 'credit-reports');

create policy "Authenticated users can read credit reports"
  on storage.objects
  for select
  to authenticated
  using (bucket_id = 'credit-reports');

create table if not exists public.credit_report_uploads (
  id uuid primary key default gen_random_uuid(),
  cp text not null,
  cp_partner text not null,
  report_type text not null check (report_type in ('project', 'admin_logs')),
  file_name text not null,
  storage_path text not null,
  mime_type text,
  file_size bigint,
  uploaded_by uuid references auth.users(id),
  uploaded_at timestamptz not null default now()
);

create index if not exists credit_report_uploads_cp_idx
  on public.credit_report_uploads (cp);

create index if not exists credit_report_uploads_cp_partner_idx
  on public.credit_report_uploads (cp_partner);

alter table public.credit_report_uploads add column if not exists cp text;
update public.credit_report_uploads set cp = cp_partner where cp is null and cp_partner is not null;

create index if not exists credit_report_uploads_report_type_idx
  on public.credit_report_uploads (report_type);

create index if not exists credit_report_uploads_uploaded_at_idx
  on public.credit_report_uploads (uploaded_at desc);

alter table public.credit_report_uploads enable row level security;

drop policy if exists "Users can read credit report uploads" on public.credit_report_uploads;
drop policy if exists "Users can insert credit report uploads" on public.credit_report_uploads;
drop policy if exists "Users can delete credit report uploads" on public.credit_report_uploads;

create policy "Users can read credit report uploads"
  on public.credit_report_uploads
  for select
  to authenticated
  using (true);

create policy "Users can insert credit report uploads"
  on public.credit_report_uploads
  for insert
  to authenticated
  with check (true);

create policy "Users can delete credit report uploads"
  on public.credit_report_uploads
  for delete
  to authenticated
  using (true);

-- ========== credit_report_rows.sql ==========
create table if not exists public.credit_report_rows (
  id bigint generated by default as identity primary key,
  upload_id uuid not null references public.credit_report_uploads(id) on delete cascade,
  cp text not null,
  report_type text not null check (report_type in ('project', 'admin_logs')),
  sheet_name text not null,
  row_index integer not null,
  row_data jsonb not null,
  uploaded_at timestamptz not null default now()
);

create index if not exists credit_report_rows_upload_id_idx
  on public.credit_report_rows (upload_id);

create index if not exists credit_report_rows_cp_report_type_idx
  on public.credit_report_rows (cp, report_type);

alter table public.credit_report_rows enable row level security;

drop policy if exists "Users can read credit report rows" on public.credit_report_rows;
drop policy if exists "Users can insert credit report rows" on public.credit_report_rows;
drop policy if exists "Users can delete credit report rows" on public.credit_report_rows;

create policy "Users can read credit report rows"
  on public.credit_report_rows
  for select
  to authenticated
  using (true);

create policy "Users can insert credit report rows"
  on public.credit_report_rows
  for insert
  to authenticated
  with check (true);

create policy "Users can delete credit report rows"
  on public.credit_report_rows
  for delete
  to authenticated
  using (true);

-- ========== cp_contacts_table.sql ==========
create table if not exists public.cp_contacts (
  id bigint generated by default as identity primary key,
  organization text not null,
  cp_name text,
  status text,
  joined_date text,
  agreement_end_date text,
  contact_emails text,
  email_domain text,
  note text,
  row_data jsonb not null default '{}'::jsonb,
  source text not null default 'apps_script',
  synced_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.cp_contacts add column if not exists source text not null default 'apps_script';
alter table public.cp_contacts add column if not exists updated_at timestamptz not null default now();

create index if not exists cp_contacts_organization_idx
  on public.cp_contacts (organization);

create index if not exists cp_contacts_synced_at_idx
  on public.cp_contacts (synced_at desc);

alter table public.cp_contacts enable row level security;

drop policy if exists "Users can read cp contacts" on public.cp_contacts;
drop policy if exists "Users can insert cp contacts" on public.cp_contacts;
drop policy if exists "Users can update cp contacts" on public.cp_contacts;
drop policy if exists "Users can delete cp contacts" on public.cp_contacts;

create policy "Users can read cp contacts"
  on public.cp_contacts
  for select
  to authenticated
  using (true);

create policy "Users can insert cp contacts"
  on public.cp_contacts
  for insert
  to authenticated
  with check (true);

create policy "Users can update cp contacts"
  on public.cp_contacts
  for update
  to authenticated
  using (true);

create policy "Users can delete cp contacts"
  on public.cp_contacts
  for delete
  to authenticated
  using (true);

create table if not exists public.credits_user_limit (
  id uuid primary key default gen_random_uuid(),
  partner_name text not null default '',
  pic text not null default '',
  project text not null default '',
  license_end_date date,
  credits_allocated numeric not null default 0,
  credits_used numeric not null default 0,
  terms_and_condition text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id)
);

create index if not exists credits_user_limit_partner_name_idx
  on public.credits_user_limit (partner_name);

create index if not exists credits_user_limit_license_end_date_idx
  on public.credits_user_limit (license_end_date);

alter table public.credits_user_limit enable row level security;

drop policy if exists "Users can read credits user limit rows" on public.credits_user_limit;
drop policy if exists "Users can insert credits user limit rows" on public.credits_user_limit;
drop policy if exists "Users can update credits user limit rows" on public.credits_user_limit;
drop policy if exists "Users can delete credits user limit rows" on public.credits_user_limit;

create policy "Users can read credits user limit rows"
  on public.credits_user_limit
  for select
  to authenticated
  using (true);

create policy "Users can insert credits user limit rows"
  on public.credits_user_limit
  for insert
  to authenticated
  with check (true);

create policy "Users can update credits user limit rows"
  on public.credits_user_limit
  for update
  to authenticated
  using (true);

create policy "Users can delete credits user limit rows"
  on public.credits_user_limit
  for delete
  to authenticated
  using (true);
