create table if not exists public.stripe_invoices (
  id bigint generated by default as identity primary key,
  upload_id uuid not null,
  source_file text not null,
  row_index integer not null,
  uploaded_by uuid references auth.users(id),
  uploaded_at timestamptz not null default now(),
  stripe_invoice_id text,
  organization text,
  customer_email text,
  date_utc text,
  subtotal text,
  tax_amount text,
  total_amount text,
  total_before_gst text,
  total_discount_amount text,
  credits_usage text,
  raw_data jsonb not null
);

create index if not exists stripe_invoices_upload_id_idx
  on public.stripe_invoices (upload_id);

create index if not exists stripe_invoices_uploaded_at_idx
  on public.stripe_invoices (uploaded_at desc);

create index if not exists stripe_invoices_customer_email_idx
  on public.stripe_invoices (customer_email);

create index if not exists stripe_invoices_organization_idx
  on public.stripe_invoices (organization);

alter table public.stripe_invoices enable row level security;

create policy "Users can read uploaded Stripe invoices"
  on public.stripe_invoices
  for select
  to authenticated
  using (true);
